### ISSUE TITLE
Breaks on Python2 due to no-argument super() call.

### ISSUE THREAD

**Issue by mbr** [simonzack/hfilesize#1]
``` pycon
>>> from hfilesize import Format, FileSize
>>> FileSize('1k')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marc/.virtualenvs/wrimg/local/lib/python2.7/site-packages/hfilesize/hfilesize.py", line 236, in __new__
    return super().__new__(cls, size)
TypeError: super() takes at least 1 argument (0 given)
```

**Comment by mbr** [comment]
This is fixed in pull request #2 now. =)
